### ISSUE TITLE
Absolute path to the .pdb file

### ISSUE THREAD

**Issue by tim-lebedkov** [rainers/cv2pdb#45]
cv2pdb writes the absolute path to the .pdb file in the "debug/CodeView" section. If I copy the executable to a target computer, Process Explorer cannot find the .pdb file.

Could you please use the relative file name or the file name provided on the command line?

BTW, the fix for #40 works in Process Explorer and Very Sleepy, but not in AMD uProf. Something is probably still missing.

**Comment by rainers** [comment]
> cv2pdb writes the absolute path to the .pdb file in the "debug/CodeView" section. If I copy the executable to a target computer, Process Explorer cannot find the .pdb file.
> 
> Could you please use the relative file name or the file name provided on the command line?

The absolute file name is deliberately used because it has a number of advantages:
- if you move the executable, it is still found
- it is not dependent on the current directory during the build, a relative path might not be correct if the executable is not built into the current directory.

Most debuggers I know load the pdb file if it is copied into the same directory as the executable. In addition they allow specification of a search path, setting `_NT_SYMBOL_PATH` might also help.



> BTW, the fix for #40 works in Process Explorer and Very Sleepy, but not in AMD uProf. Something is probably still missing.

Can't do much without more details.

**Comment by tim-lebedkov** [comment]
I tested additionally with WinDbg and VerySleepy and both can find the .pdb file in the .exe directory.

Process Explorer is pretty important to me. Could you add an option for this?

**Comment by rainers** [comment]
Just noticed that cv2pdb has option `-p<embedded-pdb>`. Isn't this what you are looking for?

BTW: Process Explorer allows to set a search path for symbol files, too.

**Comment by tim-lebedkov** [comment]
I tested the executables with -p and without -p. Very Sleepy and WinDbg can find the .pdb file in both cases. Process Explorer can't find the .pdb until I add the directory to the search path for the symbols.

You can close this issue. I do not need any changes in the program.

If possible, please change the cv2pdb usage output so that it says -p<embedded-pdb> instead of
usage: cv2pdb [-Dversion|-C|-n|-e|-sC|-pembedded-pdb] <exe-file> [new-exe-file] [pdb-file]

The README does not show the -p<embedded-pdb> option.

**Comment by rainers** [comment]
I updated the program help output and the README.
